### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [nec-postgres/tdeforpg#1]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html) ⇒ [enc_store_key_info](https://github.com/nec-postgres/tdeforpg/blob/46a1177c4c4c8cba9e0ba647fc1b5c1decd14974/SOURCES/data_encryption/93/data_encryption.c#L637)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html) ⇒ [enc_store_old_key_info](https://github.com/nec-postgres/tdeforpg/blob/46a1177c4c4c8cba9e0ba647fc1b5c1decd14974/SOURCES/data_encryption/93/data_encryption.c#L667)

**Comment by d-jung-nec** [comment]
@ynamiki  
The memory allocated by palloc will be freed automatically at the end of each transaction, preventing memory leaks.
but, cipher key need to lasted for end of tde session or client connection.
So I cannot agree using a palloc instead of malloc.

**Comment by d-jung** [comment]
It is fixed by commit 2b3b2976153
