### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [nec-postgres/tdeforpg#2]
[An extra null pointer check is not needed in functions](http://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first) like the following.
- [enc_drop_key_info](https://github.com/nec-postgres/tdeforpg/blob/46a1177c4c4c8cba9e0ba647fc1b5c1decd14974/SOURCES/data_encryption/93/data_encryption.c#L698)
- [enc_drop_old_key_info](https://github.com/nec-postgres/tdeforpg/blob/46a1177c4c4c8cba9e0ba647fc1b5c1decd14974/SOURCES/data_encryption/93/data_encryption.c#L724)

**Comment by ynamiki** [comment]
@d-jung-nec It is recommended to create a new branch for each issue. I create the pull request #3 for this issue from a dedicated branch.

**Comment by d-jung** [comment]
@elfring @ynamiki  Thank you for your advice. I revised it as you said.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/nec-postgres/tdeforpg/commit/a6295308dfef08f0bb58b95e7773495b348342eb).
